name: Lint Darker - Validate Python Codes

on: [pull_request]

jobs:
  darker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
            python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install darker~=2.1.1 flake8 pylint==2.13.1
                    
      - name: Set commit range
        id: commit_range
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            COMMIT_RANGE=$(git rev-parse HEAD^1)...$(git rev-parse HEAD)
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            COMMIT_RANGE="${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}"
          fi
          echo "COMMIT_RANGE=${COMMIT_RANGE}" >> $GITHUB_ENV

          
      - name: Get changed files
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ env.COMMIT_RANGE }} -- '*.py')
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV
        shell: bash

      - name: Run Darker
        uses: akaihola/darker@acb622567d1a26b0c6dcbb1b171c1c8340ee6c22
        with:
            options: "--check --diff --isort --color"
            src: ${{ env.CHANGED_FILES }}
            lint: "flake8,pylint==2.13.1"
        continue-on-error: true

    #   - name: Run Flake8 Linter
    #     if: always()
    #     run: |
    #       if [ -n "${{ env.CHANGED_FILES }}" ]; then
    #         flake8 ${{ env.CHANGED_FILES }}
    #       else
    #         echo "No Python files to lint with Flake8."
    #       fi

    #   - name: Run Pylint
    #     if: always()
    #     run: |
    #       if [ -n "${{ env.CHANGED_FILES }}" ]; then
    #         pylint ${{ env.CHANGED_FILES }}
    #       else
    #         echo "No Python files to lint with Pylint."
    #       fi
