---
    name: Darker Lint
    
    on: [push, pull_request]
    
    jobs:
      darker-lint:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
        #   uses: actions/checkout@v4
          uses: actions/checkout@v2
          with:
              fetch-depth: 0
          
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'          

        - name: Determine commit range
          id: commit_range
          run: |
            if [ "${{ github.event_name }}" == "push" ]; then
              echo "range=HEAD~1..HEAD" >> $GITHUB_ENV
            else
              echo "range=${{ github.event.before }}..${{ github.sha }}" >> $GITHUB_ENV
            fi

        - name: Debug Commit Range
          run: |
              echo "Commit range: ${{ env.range }}"

        - name: Run Darker
          uses: akaihola/darker@v2.1.1
        #   uses: akaihola/darker@acb622567d1a26b0c6dcbb1b171c1c8340ee6c22
          with:
            #   options: "--check --diff --isort --color -r ${{ env.range }}"
              options: "--check --diff --isort --color"
              src: "."
              version: "~=2.1.1"
            #   lint: "flake8,pylint==2.13.1"
              lint: "ruffe"


              